ALTER TABLE subscriptions
  ADD COLUMN IF NOT EXISTS past_due_since TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS grace_period_end TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS grace_day3_sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS grace_day6_sent_at TIMESTAMPTZ;
