ALTER TABLE user_passes
  ADD COLUMN IF NOT EXISTS reminder_14_sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reminder_7_sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reminder_5_sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reminder_3_sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reminder_1_sent_at TIMESTAMPTZ;
